=== evensolberg/id3tools/sample_data/summary-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "musicbrainz_disc_id": {
            "type": "string"
        },
        "album_artist": {
            "type": "string"
        },
        "album_name": {
            "type": "string"
        },
        "track_count": {
            "type": "integer"
        },
        "disc_count": {
            "type": "integer"
        },
        "total_duration_sec": {
            "type": "integer"
        },
        "last_updated": {
            "type": "string"
        },
        "album_gain_db": {
            "type": "number"
        },
        "album_peak_gain_db": {
            "type": "number"
        },
        "album_dynamic_range_r128": {
            "type": "number"
        },
        "reference_loudness_db": {
            "type": "integer"
        },
        "tracks": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "musicbrainz_track_id": {
                            "type": "string"
                        },
                        "ISRC": {
                            "type": "string"
                        },
                        "disc_number": {
                            "type": "integer"
                        },
                        "track_number": {
                            "type": "integer"
                        },
                        "disc_count": {
                            "type": "integer"
                        },
                        "track_count": {
                            "type": "integer"
                        },
                        "album_artist": {
                            "type": "string"
                        },
                        "track_artist": {
                            "type": "string"
                        },
                        "album_name": {
                            "type": "string"
                        },
                        "track_name": {
                            "type": "string"
                        },
                        "duration_sec": {
                            "type": "integer"
                        },
                        "file_format": {
                            "type": "string"
                        },
                        "bit_depth": {
                            "type": "integer"
                        },
                        "sample_frequency_hz": {
                            "type": "integer"
                        },
                        "channels": {
                            "type": "integer"
                        },
                        "bit_rate_kbps": {
                            "type": "integer"
                        },
                        "dynamic_range_db": {
                            "type": "number"
                        },
                        "track_gain_db": {
                            "type": "number"
                        },
                        "track_peak": {
                            "type": "number"
                        }
                    },
                    "required": [
                        "musicbrainz_track_id",
                        "ISRC",
                        "disc_number",
                        "track_number",
                        "disc_count",
                        "track_count",
                        "album_artist",
                        "track_artist",
                        "album_name",
                        "track_name",
                        "duration_sec",
                        "file_format",
                        "bit_depth",
                        "sample_frequency_hz",
                        "channels",
                        "bit_rate_kbps",
                        "dynamic_range_db",
                        "track_gain_db",
                        "track_peak"
                    ]
                }
            ]
        }
    },
    "required": [
        "musicbrainz_disc_id",
        "album_artist",
        "album_name",
        "track_count",
        "disc_count",
        "total_duration_sec",
        "last_updated",
        "album_gain_db",
        "album_peak_gain_db",
        "album_dynamic_range_r128",
        "reference_loudness_db",
        "tracks"
    ]
}

=== evensolberg/id3tools/sample_data/summary-example.json
{
    "musicbrainz_disc_id": "XzPS7vW.HPHsYemQh0HBUGr8vuU-",
    "album_artist": "AC/DC",
    "album_name": "Back in Black",
    "track_count": 10,
    "disc_count": 1,
    "total_duration_sec": 200,
    "last_updated": "2024-03-10T09:26:00",
    "album_gain_db": -9.65,
    "album_peak_gain_db": 1.00416791,
    "album_dynamic_range_r128": 7.203475,
    "reference_loudness_db": 89,
    "tracks": [
        {
            "musicbrainz_track_id": "110f3d90-b0ed-497f-a352-ca581bc8025f",
            "ISRC": "AUAP08000041",
            "disc_number": 1,
            "track_number": 1,
            "disc_count": 1,
            "track_count": 10,
            "album_artist": "AC/DC",
            "track_artist": "AC/DC",
            "album_name": "Back in Black",
            "track_name": "Hell's Bells",
            "duration_sec": 20,
            "file_format": "FLAC",
            "bit_depth": 24,
            "sample_frequency_hz": 96000,
            "channels": 2,
            "bit_rate_kbps": 3240,
            "dynamic_range_db": 7.2,
            "track_gain_db": -9.4,
            "track_peak": 0.97448939
        },
        {
            "musicbrainz_track_id": "6eb73987-6b5e-42ac-b4e3-763589a09a51",
            "ISRC": "AUAP08000042",
            "disc_number": 1,
            "track_number": 2,
            "disc_count": 1,
            "track_count": 10,
            "album_artist": "AC/DC",
            "track_artist": "AC/DC",
            "album_name": "Back in Black",
            "track_name": "Shoot to Thrill",
            "duration_sec": 20,
            "file_format": "FLAC",
            "bit_depth": 24,
            "sample_frequency_hz": 96000,
            "channels": 2,
            "bit_rate_kbps": 3307,
            "dynamic_range_db": 6.3,
            "track_gain_db": -9.43,
            "track_peak": 0.96631044
        }
    ]
}
